// API response codes used by GET /keys/public (getPublicKeyByEmail)

export const API_GET_PUBLIC_KEY_BY_EMAIL_CODE = {
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_EMAIL_OWNER: "INVALID_EMAIL_OWNER",
  PUBLIC_KEYS_NOT_FOUND: "PUBLIC_KEYS_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PUBLIC_KEYS_FOUND: "PUBLIC_KEYS_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type GetPublicKeyByEmailCode =
  (typeof API_GET_PUBLIC_KEY_BY_EMAIL_CODE)[keyof typeof API_GET_PUBLIC_KEY_BY_EMAIL_CODE];
