import { COLORS } from "../constants";

export const lightColors = {
  primary: COLORS.primary,
  secondary: COLORS.secondary,
  tertiary: COLORS.tertiary,
  success: COLORS.success,
  info: COLORS.info,
  warning: COLORS.warning,
  error: COLORS.error,
  background: COLORS.white,
  backgroundSecondary: COLORS.tertiaryWhite,
  surface: COLORS.white,
  surfaceAlternative: COLORS.silver,
  text: COLORS.greyscale900,
  textSecondary: COLORS.grayscale700,
  textMuted: COLORS.gray,
  textPrimary: COLORS.primary,
  inputBackground: COLORS.greyscale500,
  inputBorder: COLORS.greyscale500,
  inputPlaceholder: COLORS.black,
  inputPlaceholderSubtle: COLORS.greyscale500,
  inputFocusedBackground: COLORS.tansparentPrimary,
  inputFocusedBorder: COLORS.primary,
  buttonSecondaryBackground: COLORS.tansparentPrimary,
  buttonSecondaryText: COLORS.black,
  border: COLORS.grayscale200,
  divider: COLORS.greyscale300,
  icon: COLORS.greyscale900,
  iconSecondary: COLORS.gray3,
  iconMuted: "#BCBCBC",
  iconPrimary: COLORS.primary,
};

export const darkColors = {
  primary: COLORS.primary,
  secondary: COLORS.secondary,
  tertiary: COLORS.tertiary,
  success: COLORS.success,
  info: COLORS.info,
  warning: COLORS.warning,
  error: COLORS.error,
  background: COLORS.dark1,
  backgroundSecondary: COLORS.dark1,
  surface: COLORS.dark2,
  surfaceAlternative: COLORS.dark3,
  text: COLORS.white,
  textSecondary: COLORS.grayscale200,
  textMuted: COLORS.grayscale400,
  textPrimary: COLORS.white,
  inputBackground: COLORS.dark2,
  inputBorder: COLORS.dark2,
  inputPlaceholder: COLORS.grayTie,
  inputPlaceholderSubtle: COLORS.greyscale600,
  inputFocusedBackground: COLORS.tansparentPrimary,
  inputFocusedBorder: COLORS.primary100,
  buttonSecondaryBackground: COLORS.dark3,
  buttonSecondaryText: COLORS.white,
  border: COLORS.greyScale800,
  divider: COLORS.dark3,
  icon: COLORS.white,
  iconSecondary: COLORS.white,
  iconMuted: "#BCBCBC",
  iconPrimary: COLORS.white,
};
